### PR TITLE
Working Auton Code

### PR DESCRIPTION
**Pull request by nsarda54**
It works for both red and blue mountains. Ignore first commit, look at the second one with the RedMountainAuto, and BlueMountainAuto, thats titled "Has Both Blue and Red Mountain Autons".

### CODE REVIEW

**Comment by nsarda54** [comment]
What is this? Did you merge my pull request?

**Comment by TimMagoun** [comment]
Yes

**Comment by nsarda54** [comment]
Oh ok. Did you look at the code yet?

**Comment by TimMagoun** [comment]
Dude i had to solve all ur merge conflicts...

**Comment by nsarda54** [comment]
What?

**Comment by TimMagoun** [comment]
Yes i merged it to master

**Comment by nsarda54** [comment]
Did you check out our code? Is it ok?

**Pull request merged**
