### PR TITLE
Auton Commit - Highly experimental values, could explode

### PR DESCRIPTION
**Pull request by nsarda54**
Caution, wear hazmat suit when deploying code.

### CODE REVIEW

**Comment by TimMagoun** [comment]
Dont create a pull request for super unstable code...

**Comment by nsarda54** [comment]
Its not that unstable.

**Comment by aravindkoneru** [comment]
@nsarda54 Can you explain why you want different methods for turning left and right? I don't see the reason for it.

**Comment by nsarda54** [comment]
I think that was the old one... Can you still see that? Should I commit
just the new one again?

**Comment by aravindkoneru** [comment]
Sorry, that was my bad. I didn't look at the diff for your Nov 8. commit.

**Pull request merged**
